version: 2.32.4

services:
  # Server
  pqc_server1:
    image: "arm64v8/ubuntu:latest"
    container_name: "pqc_server1"
    tty: "True"
    stdin_open: "True"
    restart: "always"
    ports:
      - "1318:1318"
    volumes:
      - "..:/socket"
    command:
      ["bash"]
    networks: 
      - "pqc_network"
  
  # Client
  pqc_client1:
    image: "arm64v8/ubuntu:latest"
    container_name: "pqc_client1"
    tty: "True"
    stdin_open: "True"
    restart: "always"
    ports:
      - "1319:1319"
    volumes:
      - "..:/socket"
    command:
      ["bash"]
    networks: 
      - "pqc_network"

networks:
  pqc_network:
    name: pqc_network
    driver: bridge






