# version: 2.33.0

services:
  # Server
  pqc_server:
    image: "mizzou-pqc"
    container_name: "pqc_server"
    tty: "True"
    stdin_open: "True"
    restart: "always"
    ports:
      - "1316:1316"
    volumes:
      - "..:/home/socket"
    command:
      ["bash"]
    networks: 
      - "pqc_network"
  
  # Client
  pqc_client:
    image: "mizzou-pqc"
    container_name: "pqc_client"
    tty: "True"
    stdin_open: "True"
    restart: "always"
    ports:
      - "1317:1317"
    volumes:
      - "..:/home/socket"
    command:
      ["bash"]
    networks: 
      - "pqc_network"

networks:
  pqc_network:
    name: pqc_network
    driver: bridge






